Update failure test workflow
Signed-off-by: Babak K. Shandiz <babakks@github.com>

diff --git a/.github/workflows/manual-dispatch.yml b/.github/workflows/manual-dispatch.yml
--- a/.github/workflows/manual-dispatch.yml
+++ b/.github/workflows/manual-dispatch.yml
@@ -16,47 +16,49 @@ env:
   RESULT_STRING: ${{ github.event.inputs.result_string }}
   SLEEP_TIMEOUTS: ${{ github.event.inputs.sleep_timeout }}
   _RUN: |
-    idx=$1
-    ts=( $SLEEP_TIMEOUTS )
-    sleep "${ts[$idx]}"
-    step_num=$((idx+1))
-    if [ "${RESULT_STRING:$idx:1}" = "T" ]; then
-      echo "Step $step_num passed"
-    else
-      echo "Step $step_num failed"
-      exit 1
-    fi
+    play() {
+        idx=$1
+        ts=( $SLEEP_TIMEOUTS )
+        sleep "${ts[$idx]}"
+        step_num=$((idx+1))
+        if [ "${RESULT_STRING:$idx:1}" = "T" ]; then
+          echo "Step $step_num passed"
+        else
+          echo "Step $step_num failed"
+          exit 1
+        fi
+    }
 
 jobs:
   normal:
     runs-on: ubuntu-latest
     steps:
       - name: Step 1
-        run: eval "$_RUN" 0
+        run: eval "$_RUN"; play 0
       - name: Step 2
-        run: eval "$_RUN" 1
+        run: eval "$_RUN"; play 1
       - name: Step 3
-        run: eval "$_RUN" 2
+        run: eval "$_RUN"; play 2
       - name: Step 4
-        run: eval "$_RUN" 3
+        run: eval "$_RUN"; play 3
       - name: Step 5
-        run: eval "$_RUN" 4
+        run: eval "$_RUN"; play 4
 
   continue-on-error:
     runs-on: ubuntu-latest
     steps:
       - name: Step 1
         continue-on-error: true
-        run: eval "$_RUN" 0
+        run: eval "$_RUN"; play 0
       - name: Step 2
         continue-on-error: true
-        run: eval "$_RUN" 1
+        run: eval "$_RUN"; play 1
       - name: Step 3
         continue-on-error: true
-        run: eval "$_RUN" 2
+        run: eval "$_RUN"; play 2
       - name: Step 4
         continue-on-error: true
-        run: eval "$_RUN" 3
+        run: eval "$_RUN"; play 3
       - name: Step 5
         continue-on-error: true
-        run: eval "$_RUN" 4
+        run: eval "$_RUN"; play 4
